### ISSUE TITLE
Not able to introspect empty supergraph API

### ISSUE THREAD

**Issue by codingkarthik** [hasura/graphql-engine#10338]
### What is the current behaviour?

![empty_project_bug](https://github.com/user-attachments/assets/b3913509-5e18-40c6-811a-32ed90ea332a)

### What is the expected behaviour?

There should be no errors.

### How to reproduce the issue?

Followed the steps [here](https://hasura.io/docs/3.0/getting-started/build/init-supergraph) and doing the step 4 fails with the following error:

```json
{
  "errors": [
    {
      "message": "Failed to fetch",
      "stack": "TypeError: Failed to fetch\n    at https://console.hasura.io/assets/vendor-BLBR2gr0.js:367:3975\n    at schemaFetcher (https://console.hasura.io/assets/GraphiQLHeaders-togRCAWA.js:103:30695)\n    at https://console.hasura.io/assets/GraphiQLHeaders-togRCAWA.js:19:810\n    at fetchIntrospectionData (https://console.hasura.io/assets/GraphiQLHeaders-togRCAWA.js:71:4616)\n    at https://console.hasura.io/assets/GraphiQLHeaders-togRCAWA.js:71:5063\n    at https://console.hasura.io/assets/GraphiQLHeaders-togRCAWA.js:71:5242\n    at a2 (https://console.hasura.io/assets/vendor-BLBR2gr0.js:40:24296)\n    at qf (https://console.hasura.io/assets/vendor-BLBR2gr0.js:40:42451)\n    at S5 (https://console.hasura.io/assets/vendor-BLBR2gr0.js:40:36652)\n    at Du (https://console.hasura.io/assets/vendor-BLBR2gr0.js:38:3288)\n    at Lle (https://console.hasura.io/assets/vendor-BLBR2gr0.js:40:41328)\n    at ac (https://console.hasura.io/assets/vendor-BLBR2gr0.js:40:40312)\n    at GU (https://console.hasura.io/assets/vendor-BLBR2gr0.js:40:35759)\n    at S (https://console.hasura.io/assets/vendor-BLBR2gr0.js:25:1535)\n    at MessagePort.B (https://console.hasura.io/assets/vendor-BLBR2gr0.js:25:1894)"
    }
  ]
}
```

1.
2.
3.

**Comment by codingkarthik** [comment]
FWIW, I'm using the Brave browser, trying the same link in the Firefox browser works, so not sure if it is a bug.

**Comment by savanipoojan78** [comment]
In Brave bowser just turn off the Shields and it should work 
<img width="1089" alt="Screenshot 2024-07-15 at 3 09 21 PM" src="https://github.com/user-attachments/assets/917214d3-5a60-4d61-8ba0-24bf906d6567">
