### ISSUE TITLE
Error while Exporting the Hasura GraphQL schema

### ISSUE THREAD

**Issue by nitishk72** [hasura/graphql-engine#2056]
I am trying to export the graphql schema but I am getting this error.
This link is currently active now. https://heroku-hasura.herokuapp.com/console

![image](https://user-images.githubusercontent.com/15886737/56633691-cc3c6a00-667c-11e9-9f16-2b85f6133cf2.png)
```
nitishk72@JS-Guy MINGW64 ~/Desktop/heroku-hasura-graphql (master)
$ apollo schema:download --endpoint https://heroku-hasura.herokuapp.com/console
  √ Loading Apollo Project
  × Saving schema to schema.json
    → Response not successful: Received status code 404
ServerError: Response not successful: Received status code 404
    at Object.exports.throwServerError (C:/Users/nitishk72/AppData/Roaming/npm/node_modules/apollo/node_modules/apollo-link-http-common/lib/index.js:23:17)
    at C:/Users/nitishk72/AppData/Roaming/npm/node_modules/apollo/node_modules/apollo-link-http-common/lib/index.js:48:21

nitishk72@JS-Guy MINGW64 ~/Desktop/heroku-hasura-graphql (master)
$ npx gq https://heroku-hasura.herokuapp.com/console --introspect > schema.graphql
npx: installed 272 in 9.443s
C:\Users\nitishk72\AppData\Roaming\npm-cache\_npx\13888\node_modules\gq\gq.js:19
            var linksnumber = links.length;
                                    ^

TypeError: Cannot read property 'length' of undefined
    at C:\Users\nitishk72\AppData\Roaming\npm-cache\_npx\13888\node_modules\gq\gq.js:19:30
    at Request._callback (C:\Users\nitishk72\AppData\Roaming\npm-cache\_npx\13888\node_modules\gq\node_modules\google\lib\google.js:96:7)
    at Request.self.callback (C:\Users\nitishk72\AppData\Roaming\npm-cache\_npx\13888\node_modules\gq\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\nitishk72\AppData\Roaming\npm-cache\_npx\13888\node_modules\gq\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\nitishk72\AppData\Roaming\npm-cache\_npx\13888\node_modules\gq\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
```

**Comment by ecthiender** [comment]
@nitishk72 graphql is served at `/v1alpha1/graphql`. So the endpoint should be `https://heroku-hasura.herokuapp.com/v1alpha1/graphql`

**Comment by nitishk72** [comment]
Thanks @shahidhk

**Comment by evanbiederstedt** [comment]
```
C:\Users\nitishk72\AppData\Roaming\npm-cache\_npx\13888\node_modules\gq\gq.js:19
            var linksnumber = links.length;
```

This is using the library `gq` here: https://www.npmjs.com/package/gq

This has been incorrectly installed, which is causing your error. Please remove this package from `node_modules`

This is the correct library: https://www.npmjs.com/package/graphqurl

I believe that explains the error above.
