### ISSUE TITLE
[ERROR] Hasura console is not able to reach... and http: panic serving 127.0.0.1.

### ISSUE THREAD

**Issue by mathieutu** [hasura/graphql-engine#2862]
Hello, 
I'm trying to launch hasura console with a just deployed hasura herokuapp.

I've followed the "One-click deployment on Heroku" tutorial followed by https://docs.hasura.io/1.0/graphql/manual/migrations/existing-database.html
	
Nothing more.

We've tried on a Ubuntu machine, and Mac OSX 10.13.6

Hasura version: 
```
INFO hasura cli                                    version=v1.0.0-beta.6
INFO hasura graphql engine                         endpoint="https://xxxx.herokuapp.com" version=v1.0.0-beta.6
```

I have the `Hasura console is not able to reach your Hasura GraphQL engine instance. Please ensure that your instance is running and the endpoint is configured correctly.` error, when the browser try to reach `http://localhost:9693/apis/migrate/settings`. No problem reaching hasura instance on heroku.

The server is launch, and http://localhost:9693 is responding (404).

I've tried a curl on the url :
```bash
$curl 'http://localhost:9693/apis/migrate/settings'
curl: (52) Empty reply from server
```

On server side there is a go error:

```
http: panic serving 127.0.0.1:53887: runtime error: index out of range
goroutine 372 [running]:
net/http.(*conn).serve.func1(0xc42031e640)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x17329c0, 0x1c34950)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/hasura/graphql-engine/cli/migrate/database/hasuradb.(*HasuraDB).GetSetting(0xc4200aa150, 0x182ce32, 0xe, 0x67, 0x0, 0x0, 0xc4200aa0e0)
	/go/src/github.com/hasura/graphql-engine/cli/migrate/database/hasuradb/settings.go:172 +0x74f
github.com/hasura/graphql-engine/cli/migrate.(*Migrate).GetSetting(0xc4201ba160, 0x182ce32, 0xe, 0x67, 0xc4200a2300, 0xc42026c410, 0xc4201ba160)
	/go/src/github.com/hasura/graphql-engine/cli/migrate/migrate.go:280 +0x4c
github.com/hasura/graphql-engine/cli/migrate/api.SettingsAPI(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/migrate/api/settings.go:58 +0x75c
github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin/context.go:104 +0x43
github.com/hasura/graphql-engine/cli/commands.setDataPath.func1(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/commands/console.go:206 +0xd0
github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin/context.go:104 +0x43
github.com/hasura/graphql-engine/cli/commands.setFilePath.func1(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/commands/console.go:214 +0x105
github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin/context.go:104 +0x43
github.com/hasura/graphql-engine/cli/commands.setLogger.func1(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/commands/console.go:228 +0x9e
github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin/context.go:104 +0x43
github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4200a2b40, 0xc4201ba0b0)
	/go/src/github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin/gin.go:332 +0x585
github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4200a2b40, 0x18b8fc0, 0xc42048c460, 0xc4200ae000)
	/go/src/github.com/hasura/graphql-engine/cli/vendor/github.com/gin-gonic/gin/gin.go:296 +0x153
net/http.serverHandler.ServeHTTP(0xc420177a00, 0x18b8fc0, 0xc42048c460, 0xc4200ae000)
	/usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc42031e640, 0x18b9b40, 0xc420164100)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2798 +0x27b
```

Thank you for your help.
Matt'.

**Comment by ecthiender** [comment]
Hi Matt, can you share the contents of the `config.yaml`?

**Comment by mathieutu** [comment]
Oh sh*t, I prepared it and forgot to join the link, sorry!

https://gist.github.com/3b3a4ec759f30741f86b6a0d09e6c8da

**Comment by mathieutu** [comment]
@shahidhk @arvi3411301 thanks for this quick fix.

Do you have any idea when it will be released?

Thanks.
