### ISSUE TITLE
ETIMEDOUT running hasura on heroku 

### ISSUE THREAD

**Issue by andycmaj** [hasura/graphql-engine#3885]
getting frequent ETIMEDOUT errors calling the api using graphql-request.

```
 [FetchError]: request to https://***.herokuapp.com/v1/graphql failed, reason: connect ETIMEDOUT **.**.**.**:443
    at ClientRequest.<anonymous> (/usr/local/app/consumers/.build/webpack:/node_modules/cross-fetch/node_modules/node-fetch/lib/index.es.js:1389:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'request to https://***.herokuapp.com/v1/graphql failed, reason: connect ETIMEDOUT **.**.**.**:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
```

<img width="758" alt="Screen Shot 2020-02-13 at 11 46 45 PM" src="https://user-images.githubusercontent.com/97470/74511570-2122c880-4ebb-11ea-8ba0-6fb593654b1c.png">
<img width="763" alt="Screen Shot 2020-02-13 at 11 46 36 PM" src="https://user-images.githubusercontent.com/97470/74511572-22ec8c00-4ebb-11ea-9a72-591dd096a654.png">

this happens in multiple heroku environments, one with `HASURA_GRAPHQL_PG_TIMEOUT:300`, the other without any value for this.

i'm not sure where to start debugging this, so any help woudl be appreciated.

using `graphql-request` as my client, FWIW. 

thank you

**Comment by ecthiender** [comment]
The timeout is between the client and Hasura. So setting `HASURA_GRAPHQL_PG_TIMEOUT` shouldn't matter.

Are you running on the free-tier of Heroku? The free-tier of Heroku puts the container to sleep after 30 mins of inactivity. And then any subsequent request will wake it up, but it takes a while. Is it possible to verify if this is not causing the issue?

**Comment by andycmaj** [comment]
no i originally suspected that as well, but then I upgraded to hobby, which should be always-on according to their docs. 
still seems to happen about the same.

**Comment by andycmaj** [comment]
heroku response time metrics don't seem to be suspicious...

<img width="377" alt="Screen Shot 2020-02-14 at 11 37 08 AM" src="https://user-images.githubusercontent.com/97470/74561887-62988f80-4f1e-11ea-83a2-2d9439e697cb.png">
<img width="1230" alt="Screen Shot 2020-02-14 at 11 36 57 AM" src="https://user-images.githubusercontent.com/97470/74561889-63c9bc80-4f1e-11ea-9738-526e9bf43600.png">

**Comment by andycmaj** [comment]
@ecthiender

**Comment by ecthiender** [comment]
Are there any logs on Hasura when this timeout happens? If yes, can you share them as well?

**Comment by andycmaj** [comment]
attaching some logs a few minutes before and after an occurrence:

# rollbar log
Received On
2020-02-19 13:08:32 PST
Notifier Timestamp
2020-02-19 13:08:33 PST
```
FetchError: request to https://botany-db-staging.herokuapp.com/v1/graphql failed, reason: connect ETIMEDOUT 34.200.167.100:443 (Most recent call first)
at ClientRequest.<anonymous> (/usr/local/app/consumers/.build/webpack:/node_modules/cross-fetch/node_modules/node-fetch/lib/index.es.js line 1389 col 10)
at ClientRequest.emit (events.js line 210 col 4)
at TLSSocket.socketErrorListener (_http_client.js line 406 col 8)
at TLSSocket.emit (events.js line 210 col 4)
at emitErrorNT (internal/streams/destroy.js line 92 col 7)
at emitErrorAndCloseNT (internal/streams/destroy.js line 60 col 2)
at processTicksAndRejections (internal/process/task_queues.js line 80 col 20)

```

# hasura log 
```
2020-02-19T21:08:05.434230+00:00 app[web.1]: {"type":"query-log","timestamp":"2020-02-19T21:08:05.434+0000","level":"info","detail":{"request_id":"0c53593d-168e-4545-aa8c-581c9639552c","generated_sql":{"dataSource_by_pk":{"prepared_arguments":["{\"x-hasura-role\":\"admin\"}","slack"],"query":"SELECT  coalesce((json_agg(\"root\" )->0), 'null' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"id\" AS \"id\", \"_0_root.base\".\"data\" AS \"data\", \"_0_root.base\".\"created_at\" AS \"created_at\", \"_0_root.base\".\"updated_at\" AS \"updated_at\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"dataSource\"  WHERE ((\"public\".\"dataSource\".\"id\") = ($2))     ) AS \"_0_root.base\"      ) AS \"_2_root\"      "}},"query":{"variables":{"dataSourceId":"slack"},"query":"query GetDataSource($dataSourceId: String!) {\n  dataSource_by_pk(id: $dataSourceId) {\n    ...DataSource\n  }\n}\n\nfragment DataSource on dataSource {\n  id\n  data\n  created_at\n  updated_at\n}\n"}}}
2020-02-19T21:08:06.434771+00:00 app[web.1]: {"type":"http-log","timestamp":"2020-02-19T21:08:05.434+0000","level":"info","detail":{"operation":{"query_execution_time":2.076884e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"0c53593d-168e-4545-aa8c-581c9639552c","response_size":323},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"44.233.150.221","method":"POST","content_encoding":"gzip"}}}
2020-02-19T21:08:33.435429+00:00 heroku[router]: at=info method=POST path="/v1/graphql" host=botany-db-staging.herokuapp.com request_id=2a30e2d9-d32f-4fed-8ac0-f9cb9feb996e fwd="34.221.255.7" dyno=web.1 connect=1ms service=5ms status=200 bytes=423 protocol=https
2020-02-19T21:08:33.431555+00:00 app[web.1]: {"type":"query-log","timestamp":"2020-02-19T21:08:33.431+0000","level":"info","detail":{"request_id":"2a30e2d9-d32f-4fed-8ac0-f9cb9feb996e","generated_sql":{"teamDataSource":{"prepared_arguments":["{\"x-hasura-role\":\"admin\"}","slack","TGXBHBZ1N"],"query":"SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"id\" AS \"id\", \"_0_root.base\".\"data\" AS \"data\", \"_0_root.base\".\"externalId\" AS \"externalId\", \"_0_root.base\".\"teamId\" AS \"teamId\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"teamDataSource\"  WHERE (((\"public\".\"teamDataSource\".\"dataSourceId\") = ($2)) AND ((\"public\".\"teamDataSource\".\"externalId\") = ($3)))     ) AS \"_0_root.base\"      ) AS \"_2_root\"      "}},"query":{"variables":{"externalTeamId":"TGXBHBZ1N","dataSourceId":"slack"},"query":"query GetTeamDataSourceByExternalId($externalTeamId: String!, $dataSourceId: String!) {\n  teamDataSource(where: {dataSourceId: {_eq: $dataSourceId}, externalId: {_eq: $externalTeamId}}) {\n    ...TeamDataSource\n  }\n}\n\nfragment TeamDataSource on teamDataSource {\n  id\n  data\n  externalId\n  teamId\n}\n"}}}
2020-02-19T21:08:34.485438+00:00 heroku[router]: at=info method=POST path="/v1/graphql" host=botany-db-staging.herokuapp.com request_id=aaa0d92e-20d9-4951-b543-d652992d8617 fwd="34.221.255.7" dyno=web.1 connect=0ms service=5ms status=200 bytes=423 protocol=https
2020-02-19T21:08:34.433515+00:00 app[web.1]: {"type":"http-log","timestamp":"2020-02-19T21:08:33.431+0000","level":"info","detail":{"operation":{"query_execution_time":2.797155e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"2a30e2d9-d32f-4fed-8ac0-f9cb9feb996e","response_size":182},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"34.221.255.7","method":"POST","content_encoding":"gzip"}}}
2020-02-19T21:08:34.828723+00:00 heroku[router]: at=info method=POST path="/v1/graphql" host=botany-db-staging.herokuapp.com request_id=ae195dd9-1d00-491c-b02a-d66bfe3b1560 fwd="34.221.255.7" dyno=web.1 connect=1ms service=5ms status=200 bytes=423 protocol=https
2020-02-19T21:08:35.311532+00:00 heroku[router]: at=info method=POST path="/v1/graphql" host=botany-db-staging.herokuapp.com request_id=03d320fa-a922-4ae0-ba9f-39a45c6da512 fwd="34.221.255.7" dyno=web.1 connect=1ms service=7ms status=200 bytes=423 protocol=https
2020-02-19T21:08:35.434010+00:00 app[web.1]: {"type":"query-log","timestamp":"2020-02-19T21:08:34.481+0000","level":"info","detail":{"request_id":"aaa0d92e-20d9-4951-b543-d652992d8617","generated_sql":{"teamDataSource":{"prepared_arguments":["{\"x-hasura-role\":\"admin\"}","slack","TGXBHBZ1N"],"query":"SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"id\" AS \"id\", \"_0_root.base\".\"data\" AS \"data\", \"_0_root.base\".\"externalId\" AS \"externalId\", \"_0_root.base\".\"teamId\" AS \"teamId\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"teamDataSource\"  WHERE (((\"public\".\"teamDataSource\".\"dataSourceId\") = ($2)) AND ((\"public\".\"teamDataSource\".\"externalId\") = ($3)))     ) AS \"_0_root.base\"      ) AS \"_2_root\"      "}},"query":{"variables":{"externalTeamId":"TGXBHBZ1N","dataSourceId":"slack"},"query":"query GetTeamDataSourceByExternalId($externalTeamId: String!, $dataSourceId: String!) {\n  teamDataSource(where: {dataSourceId: {_eq: $dataSourceId}, externalId: {_eq: $externalTeamId}}) {\n    ...TeamDataSource\n  }\n}\n\nfragment TeamDataSource on teamDataSource {\n  id\n  data\n  externalId\n  teamId\n}\n"}}}
2020-02-19T21:08:35.434020+00:00 app[web.1]: {"type":"http-log","timestamp":"2020-02-19T21:08:34.481+0000","level":"info","detail":{"operation":{"query_execution_time":2.998873e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"aaa0d92e-20d9-4951-b543-d652992d8617","response_size":182},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"34.221.255.7","method":"POST","content_encoding":"gzip"}}}
2020-02-19T21:08:35.434070+00:00 app[web.1]: {"type":"query-log","timestamp":"2020-02-19T21:08:34.481+0000","level":"info","detail":{"request_id":"ae195dd9-1d00-491c-b02a-d66bfe3b1560","generated_sql":{"teamDataSource":{"prepared_arguments":["{\"x-hasura-role\":\"admin\"}","slack","TGXBHBZ1N"],"query":"SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"id\" AS \"id\", \"_0_root.base\".\"data\" AS \"data\", \"_0_root.base\".\"externalId\" AS \"externalId\", \"_0_root.base\".\"teamId\" AS \"teamId\"       ) AS \"_1_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"teamDataSource\"  WHERE (((\"public\".\"teamDataSource\".\"dataSourceId\") = ($2)) AND ((\"public\".\"teamDataSource\".\"externalId\") = ($3)))     ) AS \"_0_root.base\"      ) AS \"_2_root\"      "}},"query":{"variables":{"externalTeamId":"TGXBHBZ1N","dataSourceId":"slack"},"query":"query GetTeamDataSourceByExternalId($externalTeamId: String!, $dataSourceId: String!) {\n  teamDataSource(where: {dataSourceId: {_eq: $dataSourceId}, externalId: {_eq: $externalTeamId}}) {\n    ...TeamDataSource\n  }\n}\n\nfragment TeamDataSource on teamDataSource {\n  id\n  data\n  externalId\n  teamId\n}\n"}}}
2020-02-19T21:08:35.434071+00:00 app[web.1]: {"type":"http-log","timestamp":"2020-02-19T21:08:34.481+0000","level":"info","detail":{"operation":{"query_execution_time":2.313124e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"ae195dd9-1d00-491c-b02a-d66bfe3b1560","response_size":182},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"34.221.255.7","method":"POST","content_encoding":"gzip"}}}
```

## full log file

[botany-db-staging-logs-1582146532021.txt](https://github.com/hasura/graphql-engine/files/4227473/botany-db-staging-logs-1582146532021.txt)

don't see anything that looks like an error

**Comment by andycmaj** [comment]
see a few random 404s

```
2020-02-19T21:15:08.201272+00:00 app[web.1]: {"type":"http-log","timestamp":"2020-02-19T21:15:08.200+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"be4ec2fc-c907-4ea6-ba1d-6bfa83c46034","response_size":65,"raw_query":""},"http_info":{"status":404,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"42.106.161.74","method":"GET","content_encoding":null}}}
2020-02-19T21:15:09.170014+00:00 heroku[router]: at=info method=GET path="/" host=botany-db-staging.herokuapp.com request_id=62393b6f-69fd-4c28-b51f-fb074a1a89db fwd="209.141.121.196" dyno=web.1 connect=1ms service=2ms status=404 bytes=237 protocol=http
2020-02-19T21:15:09.202590+00:00 app[web.1]: {"type":"http-log","timestamp":"2020-02-19T21:15:08.200+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"62393b6f-69fd-4c28-b51f-fb074a1a89db","response_size":65,"raw_query":""},"http_info":{"status":404,"http_version":"HTTP/1.1","url":"/","ip":"209.141.121.196","method":"GET","content_encoding":null}}}
2020-02-19T21:15:27.445334+00:00 heroku[router]: at=info method=POST path="/v1/graphql" host=botany-db-staging.herokuapp.com request_id=956a0ac3-577f-43c0-bc87-11854ee6dbfa fwd="44.233.150.221" dyno=web.1 connect=1ms service=6ms status=200 bytes=564 protocol=https
```

attaching a larger log
[botany-db-staging-logs-1582147160561.txt](https://github.com/hasura/graphql-engine/files/4227533/botany-db-staging-logs-1582147160561.txt)

exception occurrences seem to be at 

2020-02-19 13:09:27 PST
2020-02-19 13:09:27 PST
2020-02-19 13:08:32 PST

**Comment by andycmaj** [comment]
any advice on additional debugging?

**Comment by ecthiender** [comment]
@andycmaj there is nothing on the hasura logs. Looks like hasura doesn't receive the requests. 

Can you explain in more details when does the timeout happen? Does it happen when running a particular query? Or is it happening for all queries?

Also, if you can attach the relevant logs it will be more useful. Just the logs right before and after the timeout happens.

PS: the 404s are because some client is trying to `GET` the `/v1/graphql` endpoint.

**Comment by andycmaj** [comment]
just to close this out, i believe the problem we ran into was related to this: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

we're running processes that make gql requests to the same endpoint in multiple docker containers across a cluster.

i think it's probably safe to say that the root cause here is external to yuo guys.
