### ISSUE TITLE
docker-compose up yields error

### ISSUE THREAD

**Issue by ORESoftware** [hasura/graphql-engine#4468]
I am following these instructions:
https://hasura.io/docs/1.0/graphql/manual/getting-started/docker-simple.html

when I run:

```bash
docker-compose up
```

I get this error:

```shell
oleg@xps:~/codes/ores/phoenix-ML-graphql/hasura$ docker-compose up -d
Traceback (most recent call last):
  File "/home/oleg/.local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/home/oleg/.local/lib/python2.7/site-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/home/oleg/.local/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname

```

the `docker-compose.yaml` file is like so:

```yaml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.1.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```

**Comment by GavinRay97** [comment]
Hey, this seems to be an issue outside of Hasura.

A search for this problem leads to comments on this thread:
https://github.com/docker/docker-py/issues/1502

Which suggest the following as solutions:
```bash
cp -r /usr/local/lib/python2.7/dist-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports
```
Or
```bash
sudo pip uninstall docker docker-compose
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install docker docker-compose
```
Or
```
sudo apt-get remove python-configparser
```
Or
```
sudo apt install python-backports.ssl-match-hostname
```

**Comment by tirumaraiselvan** [comment]
Closing this as the question has been answered above. Pls comment/reopen if you have further questions.
