### ISSUE TITLE
Auto-apply migrations/metadata version breaks the app

### ISSUE THREAD

**Issue by juliopiubello** [hasura/graphql-engine#5172]
Hi everyone

I am trying to auto-apply migrations/metadata for review apps at heroku, so when a new PR is open it will set a new postgresql db for the app and then the migration should run before start the server

here is the code I'm trying for the Dockerfile

```
FROM hasura/graphql-engine:v1.2.2.cli-migrations-v2

COPY ./hasura/migrations /hasura-migrations
COPY ./hasura/metadata /hasura-metadata

ENV HASURA_GRAPHQL_ENABLE_CONSOLE=true
ENV HASURA_GRAPHQL_DEV_MODE=true

CMD graphql-engine \
    --database-url $DATABASE_URL \
    serve \
    --server-port $PORT
```

but it throwrs this error at heroku:

> 2020-06-22T13:31:10.370671+00:00 app[web.1]: {"timestamp":"2020-06-22T13:31:10.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"database url for migrations is set by HASURA_GRAPHQL_DATABASE_URL"}}
2020-06-22T13:31:10.371824+00:00 app[web.1]: {"timestamp":"2020-06-22T13:31:10.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"migrations server port env var is not set, defaulting to 9691"}}
2020-06-22T13:31:10.372946+00:00 app[web.1]: {"timestamp":"2020-06-22T13:31:10.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"server timeout is not set, defaulting to 30 seconds"}}
2020-06-22T13:31:10.373997+00:00 app[web.1]: {"timestamp":"2020-06-22T13:31:10.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"starting graphql engine temporarily on port 9691"}}
2020-06-22T13:31:10.380114+00:00 app[web.1]: {"timestamp":"2020-06-22T13:31:10.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"waiting 30 for 9691 to be ready"}}
2020-06-22T13:31:10.862336+00:00 app[web.1]: {"type":"startup","timestamp":"2020-06-22T13:31:10.861+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":9691}}}
2020-06-22T13:31:10.862353+00:00 app[web.1]: {"type":"startup","timestamp":"2020-06-22T13:31:10.861+0000","level":"info","detail":{"kind":"postgres_connection","info":{"error":"parsing database url failed"}}}
2020-06-22T13:31:10.963197+00:00 app[web.1]: {"type":"pg-client","timestamp":"2020-06-22T13:31:10.861+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(0)."}}
2020-06-22T13:31:10.963198+00:00 app[web.1]: {"type":"pg-client","timestamp":"2020-06-22T13:31:10.861+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(1)."}}
2020-06-22T13:31:10.963199+00:00 app[web.1]: {"type":"startup","timestamp":"2020-06-22T13:31:10.861+0000","level":"error","detail":{"kind":"db_migrate","info":{"internal":"could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket \"/var/run/postgresql/.s.PGSQL.5432\"?\n","path":"$","error":"connection error","code":"postgres-error"}}}
2020-06-22T13:31:40.480388+00:00 app[web.1]: {"timestamp":"2020-06-22T13:31:40.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"failed waiting for 9691"}}

If I remove the ".cli-migrations-v2" it will work but the migrations will not apply, the database url env is setting good as well as the others env variables

the hasura and metadata folders are the one exported using the hasura tools

really appreciate some help 🙏

**Comment by treystout** [comment]
I'm confused about the `9691` port myself. It seems that the docker images that have the `cli-migrations.v2` suffix don't work very well with the files/folders exported from the `hasura-cli` that's inside the image. I can get migrations to work but metadata never applies. I get a similar line in my docker output

```
{"timestamp":"2020-06-22T18:31:58.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"migrations server port env var is not set, defaulting to 9691"}}
```
I don't see a reference to that ENV var here https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#server-flag-reference

**Comment by scriptonist** [comment]
Hey @juliopiubello, can you try setting the `HASURA_GRAPHQL_DATABASE_URL` env var , and try if the error persists?

**Comment by joshmedeski** [comment]
Hey, I'm having a similar problem with my project. I'm trying to deploy through ECS with this custom image:

```dockerfile
FROM hasura/graphql-engine:v1.2.2.cli-migrations-v2
COPY ./migrations /hasura-migrations
COPY ./metadata /hasura-metadata
CMD graphql-engine \
  --database-url $HASURA_GRAPHQL_DATABASE_URL \
  serve \
  --server-port $HASURA_GRAPHQL_SERVER_PORT \
```

So I'm getting the following messages in my logs:

```
migrations server port env var is not set, defaulting to 9691
```

Finally it times out with: 

```
failed waiting for 9691
```

How do I set the `migrations server port` port? `HASURA_GRAPHQL_DATABASE_URL` seems to be unrelated.

**Comment by allpwrfulroot** [comment]
I can successfully automate migrations (not metadata) for a Heroku project and the following Dockerfile. Confirm that, for Heroku, `HASURA_GRAPHQL_DATABASE_URL` is required as an environment variable OR add `ENV HASURA_GRAPHQL_MIGRATIONS_DATABASE_ENV_VAR=DATABASE_URL` to the following Dockerfile:

```
FROM hasura/graphql-engine:v1.3.0-beta.4.cli-migrations-v2

COPY ./migrations /hasura-migrations

CMD graphql-engine \
  --database-url $DATABASE_URL \
  serve \
  --server-port $PORT
```

I can get both migrations and metadata to work locally, but on Heroku I see the following error, looks like `go` crashing: 
```
...
2020-07-04T13:18:50.834925+00:00 app[web.1]: {"timestamp":"2020-07-04T13:18:50.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"applying metadata from /hasura-metadata"}}
2020-07-04T13:18:51.135529+00:00 app[web.1]: {"level":"info","msg":"Help us improve Hasura! The cli collects anonymized usage stats which\nallow us to keep improving Hasura at warp speed. To opt-out or read more,\nvisit https://hasura.io/docs/1.0/graphql/manual/guides/telemetry.html\n","time":"2020-07-04T13:18:51Z"}
2020-07-04T13:18:51.145649+00:00 app[web.1]: {"level":"info","msg":"Applying metadata...","time":"2020-07-04T13:18:51Z"}
2020-07-04T13:18:51.184268+00:00 app[web.1]: panic: runtime error: invalid memory address or nil pointer dereference
2020-07-04T13:18:51.184273+00:00 app[web.1]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc5d97f]
2020-07-04T13:18:51.184273+00:00 app[web.1]: 
2020-07-04T13:18:51.184274+00:00 app[web.1]: goroutine 1 [running]:
2020-07-04T13:18:51.184326+00:00 app[web.1]: github.com/hasura/graphql-engine/cli/plugins.(*Config).findPluginManifestFiles.func1(0xc00063a3c0, 0x1e, 0x0, 0x0, 0x1287500, 0xc000632b10, 0x1287500, 0xc000632b10)
2020-07-04T13:18:51.184344+00:00 app[web.1]: /root/graphql-engine/cli/plugins/scanner.go:27 +0x2f
...
2020-07-04T13:18:51.185172+00:00 app[web.1]: /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
2020-07-04T13:18:51.185187+00:00 app[web.1]: github.com/hasura/graphql-engine/cli/commands.Execute(0xc00008e058, 0x0)
2020-07-04T13:18:51.185205+00:00 app[web.1]: /root/graphql-engine/cli/commands/root.go:119 +0x13a
2020-07-04T13:18:51.185222+00:00 app[web.1]: main.main()
2020-07-04T13:18:51.185238+00:00 app[web.1]: /root/graphql-engine/cli/cmd/hasura/hasura.go:11 +0x22
2020-07-04T13:18:51.240608+00:00 heroku[web.1]: Process exited with status 2
2020-07-04T13:18:51.271346+00:00 heroku[web.1]: State changed from starting to crashed
2020-07-04T13:19:01.404101+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/console/data/schema/public" host=generous-red-init-user-1ls90ww.herokuapp.com request_id=f977019e-3e96-4cf4-a501-d1d3a6df939c fwd="96.255.242.7" dyno= connect= service= status=503 bytes= protocol=https
```

Extending the timeout to 5000 has no effect, not seeing anything obvious in `cli-migrations/v2/docker-entrypoint.sh`

**Comment by scriptonist** [comment]
Hey @allpwrfulroot, That looks like a bug will fix this.

can you please try setting
`HASURA_GRAPHQL_CLI_ENVIRONMENT=default` file and see if you encounter the same error ?

**Comment by scriptonist** [comment]
@allpwrfulroot created a separate issue to track this here: https://github.com/hasura/graphql-engine/issues/5333

**Comment by scriptonist** [comment]
@joshmedeski port 9691 is used to spin up a temporary server, are you aware of anything else running on that port?

**Comment by allpwrfulroot** [comment]
> Hey @allpwrfulroot, That looks like a bug will fix this.
> 
> can you please try setting
> `HASURA_GRAPHQL_CLI_ENVIRONMENT=default` in the Dockerfile and see if you encounter the same error?

That works!

**Comment by joshmedeski** [comment]
@scriptonist I'm the `hasura/graphql-engine:v1.2.2.cli-migrations-v2` docker image so if anything else is running it's in the image. I will try exposing the `9691` port in the `Dockerfile` and see if that helps.

**Comment by age2pierre** [comment]
Hello, I had a very similar problem and here so far what I've figure out : 

- entrypoint script would failed somewhere in that `if` branch => https://github.com/hasura/graphql-engine/blob/d8481c3a1c899ccbf8092a512fcb0f4f179ff045/scripts/cli-migrations/v2/docker-entrypoint.sh#L84
- when skipping migrations (by not mounting the folders) things would work fine.
- my colleagues using docker on mac would have not problem !! So something was on with my install of docker 🤔 I use fedora 32, so I already had to disable CGroup V2 and whitelist docker to firewall to make docker work at all (as according to this article https://fedoramagazine.org/docker-and-fedora-32/).

After hours of looking around (including trying with podman, changing all the env variable posible...) the only things that worked for me was **running graphql-engine in privileged mode**.

So I guess this has something to do with fedora having SELinux mode enabled (or smth similar i'm no expert...) and as far as i've read, running container in privileged mode is not a great idea, maybe someone knows exactly what privileges is needed for the cli to work (i.e. which security_opt labels to pass to the container) ?

**Comment by mgranderath** [comment]
I've had this problem too when running the `hasura/graphql-engine:v1.3.0.cli-migrations-v2` image on AWS Fargate. I've found the problem that resolved the error for me. It seems that for some reason the `--enabled-apis=metadata` flag was causing the problem. I created my own image and simply removed that flag https://github.com/hasura/graphql-engine/blob/d8481c3a1c899ccbf8092a512fcb0f4f179ff045/scripts/cli-migrations/v2/docker-entrypoint.sh#L54

**Comment by scriptonist** [comment]
Closing, since most problems mentioned here, should be fixed by  https://github.com/hasura/graphql-engine/pull/5306 and https://github.com/hasura/graphql-engine/issues/5333

**Comment by rumsrami** [comment]
I am still having the exact same problem

**Comment by jperezr21** [comment]
@joshmedeski were you able to solve the issue with ECS? I'm having the exact same issue.
