### ISSUE TITLE
CLI: v1.2.2 nil pointer dereference

### ISSUE THREAD

**Issue by haf** [hasura/graphql-engine#5392]
```
cd schema && hasura migrate apply
Checking for update... ◐ panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x135fa96]

goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).Major(...)
	/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:131
github.com/Masterminds/semver.(*Version).Compare(0x0, 0xc000508500, 0x0)
	/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:268 +0x26
github.com/Masterminds/semver.(*Version).GreaterThan(...)
	/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:250
github.com/hasura/graphql-engine/cli/update.HasUpdate(0xc000508500, 0xc0004f91a0, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/graphql-engine/cli/update/update.go:98 +0x12d
github.com/hasura/graphql-engine/cli/commands.(*updateOptions).run(0xc000563c70, 0x1, 0xc00062fc01, 0x1689ef7)
	/root/graphql-engine/cli/commands/update-cli.go:75 +0x5fc
github.com/hasura/graphql-engine/cli/commands.glob..func1(0xc0000b9900, 0x277aac8, 0x0, 0x0)
	/root/graphql-engine/cli/commands/root.go:42 +0xc3
github.com/hasura/graphql-engine/cli/commands.NewMigrateCmd.func1(0xc0000b9900, 0x277aac8, 0x0, 0x0, 0x0, 0x0)
	/root/graphql-engine/cli/commands/migrate.go:26 +0x79
github.com/spf13/cobra.(*Command).execute(0xc0000b9900, 0x277aac8, 0x0, 0x0, 0xc0000b9900, 0x277aac8)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:805 +0x56b
github.com/spf13/cobra.(*Command).ExecuteC(0x25cb860, 0xc00045f7a0, 0xc0000301b0, 0x3)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/hasura/graphql-engine/cli/commands.Execute(0xc000092058, 0x0)
	/root/graphql-engine/cli/commands/root.go:118 +0x13a
main.main()
	/root/graphql-engine/cli/cmd/hasura/hasura.go:11 +0x22
make: *** [hs_migrate] Error 2
```

**Comment by njaremko** [comment]
Surprised this existed for this long, I was just about to open an issue with this exact error in CLI v1.3.0-beta.4

**Comment by tuanalumi** [comment]
For people reading this thread and using hasura-cli of npm: This is because the dude maintaining npm version of Hasura did not update to the latest version of CLI. Using [Official Hasura CLI](https://github.com/hasura/graphql-engine/tree/master/cli) could fix this.

**Comment by jjangga0214** [comment]
@tuanalumi Hi! I am the maintainer, and I've just published the recent versions. Thanks!
