### ISSUE TITLE
Docs for schema download without admin secret 

### ISSUE THREAD

**Issue by eaubin** [hasura/graphql-engine#5450]
The [download schema docs](https://hasura.io/docs/1.0/graphql/manual/schema/export-graphql-schema.html) should mention the differences between downloading with and without an explicit X-Hasura-Admin-Secret.  E.g. the mutationType is null when the schema is downloaded without passing the admin secret.

**Comment by Hard-Coder05** [comment]
@praveenweb @marionschleifer I would like to take this issue!
Please do mention the other differneces between downloading with and without the Admin Secret key I would add them too!

**Comment by marionschleifer** [comment]
@Hard-Coder05 feel free to just try it out and document what you notice. I'll then check it out and see if something needs to be added 🙂

**Comment by fakhrip** [comment]
I will try this one if no one have done it before... (Will open PR later this day)

**Comment by fakhrip** [comment]
I don't know if i was wrong at some point because in my case, i can't even download the schema without `X-Hasura-Admin-Secret` when the engine run with the `X-Hasura-Admin-Secret` enabled.

```shell
╭─f4r4w4y@blackrock ~/Downloads 
╰─$ gq http://localhost:8080/v1/graphql --introspect > schema-no-adminkey.graphql

Executing query... error
Error:  { Error: GraphQL error: x-hasura-admin-secret/x-hasura-access-key required, but not found
    at new ApolloError (/usr/local/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:92:26)
    at /usr/local/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:1588:34
    at /usr/local/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /usr/local/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /usr/local/lib/node_modules/graphqurl/node_modules/apollo-client/bundle.umd.js:2131:19
    at Object.next (/usr/local/lib/node_modules/graphqurl/node_modules/zen-observable/lib/Observable.js:322:23)
    at notifySubscription (/usr/local/lib/node_modules/graphqurl/node_modules/zen-observable/lib/Observable.js:135:18)
  graphQLErrors:
   [ { extensions: [Object],
       message:
        'x-hasura-admin-secret/x-hasura-access-key required, but not found' } ],
  networkError: null,
  message:
   'GraphQL error: x-hasura-admin-secret/x-hasura-access-key required, but not found',
  extraInfo: undefined }
```

**Comment by Stefmore02** [comment]
Hey @biswadeep25 

Please feel free to just try it out and document what you notice. We'll then check it out and see if something needs to be added 🤓
