### ISSUE TITLE
Hasura with Python Auth example

### ISSUE THREAD

**Issue by carlskii** [hasura/graphql-engine#6810]
Hi, Im trying to follow the Hasura/Python Auth tutorial here - https://hasura.io/docs/latest/graphql/core/actions/codegen/python-flask.html#actions-codegen-python-flask

However, there seems to be a problem with the handler when I try and test it using the example provided. e.g. 

```
POST http://localhost:5000/signup HTTP/1.1
content-type: application/json

{
  "input": {
    "email": "user@test.com",
    "password": "password123"
  }
}
```

This causes the Flask app to error e.g.: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cbourne/development/python-haura-auth/server.py", line 153, in signup_handler
    args = AuthArgs.from_request(request.get_json())
  File "/Users/cbourne/development/python-haura-auth/server.py", line 115, in from_request
    return cls(**values)
NameError: name 'values' is not defined
```

**Comment by carlskii** [comment]
I managed to resolve this. For some reason `values` never got defined.

**Comment by carlskii** [comment]
I managed to resolve this. For some reason values never got defined.
