### ISSUE TITLE
docker-compose causing error during startup

### ISSUE THREAD

**Issue by justmark0** [hasura/graphql-engine#6854]
I followed the instructions on [site](https://hasura.io/docs/latest/graphql/core/getting-started/docker-simple.html#docker-simple) to get started with Hasura using docker: 
1. I downloaded the docker-compose.yml file using ```curl https://raw.githubusercontent.com/hasura/graphql-engine/stable/install-manifests/docker-compose/docker-compose.yaml -o docker-compose.yml``` 
2. Then I ran ```docker-compose up -d``` and it caused error (here is end of it. Full version you can see [here](https://pastebin.com/LW8PNvKc)):
```Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.1', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3.9/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3.9/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3.9/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3.9/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3.9/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
I use manjaro Linux. My version of docker:
```
❯ docker --version
Docker version 20.10.6, build 370c28948e
❯ docker-compose --version
docker-compose version 1.29.1, build unknown
```
Also, I had tried to clone this repo on my computer. I moved ```install-manifests/docker-compose/docker-compose.yaml``` to the root directory of the project and run docker, since the first error from traceback is FileNotFoundError, so I thought maybe some files are missing, but it didn't help. 
How can I fix this problem?

**Comment by justmark0** [comment]
So, I fixed it by adding docker to the root group. [Here](https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue) you can find the commands I used. 

But it is strange because on the other system other docker images and containers worked, but not this one.
I hope it will work for you if you have the same issue.
