### ISSUE TITLE
npm i -g fails on node:14-buster

### ISSUE THREAD

**Issue by binary64** [hasura/graphql-engine#7176]
To reproduce:
```
docker run -it --rm node:14-buster bash -c "npm i -g hasura-cli"
```
Outputs:
```
/usr/local/bin/hasura -> /usr/local/lib/node_modules/hasura-cli/hasura

> hasura-cli@2.0.1 postinstall /usr/local/lib/node_modules/hasura-cli
> node dist/index.js


hasura-cli@2.0.1
Downloading Hasura CLI binary v2.0.1 from https://github.com/hasura/graphql-engi
ne/releases/download/v2.0.1/cli-hasura-linux-amd64

events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/hasura-cli/h
asura'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:335:14
    at FSReqCallback.oncomplete (fs.js:180:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/hasura-cli/hasura'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hasura-cli@2.0.1 postinstall: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hasura-cli@2.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-03T19_36_19_523Z-debug.log
```

**Comment by Bessonov** [comment]
hasura-cli is an external project. Please open issue in https://github.com/jjangga0214/hasura-cli.
