### ISSUE TITLE
Modify row UI does not work SQL server

### ISSUE THREAD

**Issue by vijayprasanna13** [hasura/graphql-engine#8589]
### Version Information

Server Version: v.2.7.0

### Environment

OSS

### What is the expected behaviour?

I should be able to successfully edit a row from the `Modify` tab
![Screenshot 2022-06-15 at 12 40 24 PM](https://user-images.githubusercontent.com/11921040/173765062-4a630de4-b1c5-4ca5-ae82-2b5b7c0862fa.png)

### Keywords

console, modify, mssql

### What is the current behaviour?

The form is stuck in `Saving...` status like so -
![Screenshot 2022-06-15 at 12 41 11 PM](https://user-images.githubusercontent.com/11921040/173765199-d4f97b95-be41-421d-9b13-126435c1423e.png)

and there are no network calls from the browsers that are related to the `Save` action.

Also, there are these TypeErrors that show up on the console, while editing an input box in the modify tab. (Note: this happens for non-mssql databases as well but `Save` action works for the rest).

```
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at onClick (TypedInput.js:37:5)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306:1)
    at executeDispatch (react-dom.development.js:389:1)
    at executeDispatchesInOrder (react-dom.development.js:414:1)
    at executeDispatchesAndRelease (react-dom.development.js:3278:1)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287:1)
    at forEachAccumulated (react-dom.development.js:3259:1)
```

### How to reproduce the issue?

1. Create a MSSQL table with rows in it and track it.
2. Navigate to the `Modify` section
3. Edit a column and save it.

**Comment by Varun-Choudhary** [comment]
Closing the issue as the PR is merged.
https://github.com/hasura/graphql-engine-mono/pull/4741

**Comment by vijayprasanna13** [comment]
Resolved in https://github.com/hasura/graphql-engine/commit/b2bcb03824fae940b6770867dcecfed5aace90e4
