### ISSUE TITLE
Hasura doesn't conform to graphql-ws nor the subscriptions-transport-ws spec correctly - Receiving ping/keepalive message before connection_ack 

### ISSUE THREAD

**Issue by vincentjames501** [hasura/graphql-engine#9246]
### Version Information

Server Version: 2.15.0

### Environment

OSS

### What is the current behaviour?

Similar to #7002, when using the new [protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) we receive a Ping message before a connection_ack. This causes libraries like dgs and Apollo Kotlin to throw and log errors.

```
unknown graphql-ws message while waiting for connection_ack: 'ping
```
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: graphql.GraphQLException: Acknowledgement expected from server, received OperationMessage(type=ka, payload=null, id=)
Caused by: graphql.GraphQLException: Acknowledgement expected from server, received OperationMessage(type=ka, payload=null, id=)
	at com.netflix.graphql.dgs.client.WebSocketGraphQLClient$doHandshake$1$1.invoke(WebSocketGraphQLClient.kt:138)
	at com.netflix.graphql.dgs.client.WebSocketGraphQLClient$doHandshake$1$1.invoke(WebSocketGraphQLClient.kt:134)
	at com.netflix.graphql.dgs.client.WebSocketGraphQLClient.doHandshake$lambda$7$lambda$6(WebSocketGraphQLClient.kt:134)
```

### What is the expected behaviour?

Keep alives/pings should not be sent until the connection has been acked.

### How to reproduce the issue?

Connect to any Hasura Subscription using the dgs library or Apollo Kotlin library for example.

### Any possible solutions/workarounds you're aware of?

No

**Comment by pranshi06** [comment]
Hi @vincentjames501, thank you for reporting this issue.

According to the step 2 of the [example](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#successful-connection-initialisation) in the graphql-ws protocol RFC, `ping` can be sent anytime after the socket establishment [here](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#ping). We think that the current behaviour is acceptable with respect to the RFC. 
However, we see that libraries like dgs and Apollo Kotlin assumes that pings are sent after `connection_ack`, and throws error. We will look into this and get back to you soon.

**Comment by vincentjames501** [comment]
@pranshi06 , yeah. After reading it a bit more closely I agree for the [graphql-ws](https://github.com/enisdenjo/graphql-ws) protocol. I still think for the [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) protocol the behavior is incorrect still. I logged a ticket over at Apollo Kotlin to be a bit more graceful on handling this message before connection ack.
