### ISSUE TITLE
NullPointerException on connecting to MySQL

### ISSUE THREAD

**Issue by mavarazy** [hasura/graphql-engine#9812]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.31.0

### Environment

OSS

### What is the current behaviour?

Getting NPE on connecting to some DB's, no amount of retries help :)
This is a huge setup (I think one of the largest in the world), so this might not be typical, this approach worked in previous version 2.28.0

### What is the expected behaviour?

Can't connect to MySQL DB

### How to reproduce the issue?

Not sure this is enterprise setup

### Please provide any traces or logs that could help here.

java.lang.NullPointerException: resultSet.getString("COLUMNS") must not be null
        at io.hasura.services.schemaGenerators.MySQLSchemaGenerator.queryDatabase(MySQLSchemaGenerator.kt:67)
        at io.hasura.services.schemaGenerators.BaseSchemaGenerator.getSchema(BaseSchemaGenerator.kt:36)
        at io.hasura.services.schemaGenerators.BaseSchemaGenerator.getSchema(BaseSchemaGenerator.kt:27)
        at io.hasura.services.dataConnectors.MySQLDataConnectorService.executeGetSchema(MySQLDataConnectorService.kt:64)
        at io.hasura.services.dataConnectors.BaseDataConnectorService.getSchema(BaseDataConnectorService.kt:121)
        at io.hasura.services.dataConnectors.MySQLDataConnectorService_Subclass.getSchema11753superforward(Unknown Source)
        at io.hasura.services.dataConnectors.MySQLDataConnectorService_Subclass11753function117537.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:66)
        at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:66)
        at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:34)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.hasura.services.dataConnectors.MySQLDataConnectorService_Subclass.getSchema(Unknown Source)
        at io.hasura.controllers.DataConnectorResource.getSchema(DataConnectorResource.kt:101)
        at io.hasura.controllers.DataConnectorResource_Subclass.getSchema11753superforward(Unknown Source)
        at io.hasura.controllers.DataConnectorResource_Subclass11753function117534.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:66)
        at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:66)
        at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:34)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.hasura.controllers.DataConnectorResource_Subclass.getSchema(Unknown Source)
        at io.hasura.controllers.DataConnectorResource.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

### Any possible solutions/workarounds you're aware of?

I've tried to increase timeout, but this had no effect.

FYI: @motleydev

**Comment by mavarazy** [comment]
I've rolled back to v2.8.0 for both connector & engine, and it connected, although other DB's started failing, so I had to switch to doing it manual, instead of importing huge metadata file.

Trying versions after 2.8.0 (2.8.2, 2.9.2) resulted in the same NPE, so it's most likely related to changes between 2.8.0 & 2.8.1

**Comment by mavarazy** [comment]
Fixes with 2.33.0 release
